# Generated by Django 5.1.1 on 2024-10-01 19:55

import datetime

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Podcast",
            fields=[
                ("id", models.CharField(editable=False, max_length=64, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=3)),
                ("forward_guild", models.CharField(max_length=3)),
                ("forward_channel", models.CharField(max_length=3)),
                ("url_feed", models.URLField()),
                ("url_artwork", models.URLField(null=True)),
                (
                    "date_cutoff",
                    models.DateTimeField(default=datetime.datetime(1970, 1, 1, 0, 0, tzinfo=datetime.UTC)),
                ),
                (
                    "date_checked",
                    models.DateTimeField(default=datetime.datetime(1970, 1, 1, 0, 0, tzinfo=datetime.UTC)),
                ),
                (
                    "date_updated",
                    models.DateTimeField(default=datetime.datetime(1970, 1, 1, 0, 0, tzinfo=datetime.UTC)),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Episode",
            fields=[
                ("id", models.CharField(editable=False, max_length=64, primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=3)),
                ("subtitle", models.CharField(max_length=3, null=True)),
                ("summary", models.CharField(max_length=3, null=True)),
                ("url_episode", models.URLField()),
                ("url_artwork", models.URLField(null=True)),
                ("date_published", models.DateTimeField()),
                ("date_forwarded", models.DateTimeField(null=True)),
                ("podcast", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="disco.podcast")),
            ],
        ),
    ]
