# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
        exclude: ^.idea/.*\.[ix]ml$
      - id: check-added-large-files
        exclude: ^res/.*
      - id: check-ast
        language_version: python3.12
      - id: check-case-conflict
      - id: check-docstring-first
      # - id: check-illegal-windows-names  # Not released yet
      - id: check-json
      - id: check-merge-conflict
      - id: check-toml
      - id: check-xml
      - id: check-yaml
      - id: fix-byte-order-marker
      - id: name-tests-test
      - id: pretty-format-json
        args: [ --autofix, --no-ensure-ascii ]

  - repo: https://github.com/henryiii/validate-pyproject-schema-store
    rev: 2024.10.14
    hooks:
      - id: validate-pyproject
        additional_dependencies: [ "validate-pyproject[all]", "validate-pyproject-schema-store" ]
        language_version: python3.12

  - repo: https://github.com/python-poetry/poetry
    rev: 1.8.0
    hooks:
      - id: poetry-check
      # - id: poetry-lock  # Broken in pre-commit.ci
      - id: poetry-install

  - repo: https://github.com/python-poetry/poetry-plugin-export
    rev: "1.8.0"
    hooks:
      - id: poetry-export
        args: ["--output=docs/requirements.txt", "--without-hashes", "--with", "dev"]

  - repo: https://github.com/jshwi/docsig
    rev: v0.64.0
    hooks:
      - id: docsig
        language_version: python3.12

  - repo: https://github.com/dosisod/refurb
    rev: v2.0.0
    hooks:
      - id: refurb
        language_version: python3.12

  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.6.9
    hooks:
      # Run the linter.
      - id: ruff
        language_version: python3.12
        args: [ --fix ]
      # Run the formatter.
      - id: ruff-format
        language_version: python3.12

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.11.2
    hooks:
      - id: mypy
        language_version: python3.12
        additional_dependencies:
          [ types-colorama, types-jsonschema, types-python-dateutil, types-requests ]
